const verbs = [
  { present: "awake", past: "awoke", participle: "awoken", uzbek: "uyg'onmoq" },
  { present: "be", past: "was/were", participle: "been", uzbek: "bo'lmoq" },
  { present: "beat", past: "beat", participle: "beaten", uzbek: "urmoq" },
  {
    present: "become",
    past: "became",
    participle: "become",
    uzbek: "bo'lib qolmoq",
  },
  { present: "begin", past: "began", participle: "begun", uzbek: "boshlamoq" },
  { present: "bend", past: "bent", participle: "bent", uzbek: "egmoq" },
  { present: "bet", past: "bet", participle: "bet", uzbek: "garov tikmoq" },
  { present: "bid", past: "bid", participle: "bid", uzbek: "taklif qilmoq" },
  { present: "bite", past: "bit", participle: "bitten", uzbek: "tishlamoq" },
  { present: "blow", past: "blew", participle: "blown", uzbek: "puflamoq" },
  { present: "break", past: "broke", participle: "broken", uzbek: "sindirmoq" },
  {
    present: "bring",
    past: "brought",
    participle: "brought",
    uzbek: "olib kelmoq",
  },
  {
    present: "broadcast",
    past: "broadcast",
    participle: "broadcast",
    uzbek: "efirga uzatmoq",
  },
  { present: "build", past: "built", participle: "built", uzbek: "qurmoq" },
  {
    present: "buy",
    past: "bought",
    participle: "bought",
    uzbek: "sotib olmoq",
  },
  { present: "catch", past: "caught", participle: "caught", uzbek: "ushlamoq" },
  { present: "choose", past: "chose", participle: "chosen", uzbek: "tanlamoq" },
  { present: "come", past: "came", participle: "come", uzbek: "kelmoq" },
  { present: "cost", past: "cost", participle: "cost", uzbek: "narxlanmoq" },
  { present: "cut", past: "cut", participle: "cut", uzbek: "kesmoq" },
  { present: "dig", past: "dug", participle: "dug", uzbek: "qazimoq" },
  { present: "do", past: "did", participle: "done", uzbek: "qilmoq" },
  { present: "draw", past: "drew", participle: "drawn", uzbek: "chizmoq" },
  { present: "drive", past: "drove", participle: "driven", uzbek: "haydamoq" },
  { present: "drink", past: "drank", participle: "drunk", uzbek: "ichmoq" },
  { present: "eat", past: "ate", participle: "eaten", uzbek: "yemoq" },
  { present: "fall", past: "fell", participle: "fallen", uzbek: "yiqilmoq" },
  { present: "feel", past: "felt", participle: "felt", uzbek: "his qilmoq" },
  {
    present: "fight",
    past: "fought",
    participle: "fought",
    uzbek: "jang qilmoq",
  },
  { present: "find", past: "found", participle: "found", uzbek: "topmoq" },
  { present: "fly", past: "flew", participle: "flown", uzbek: "uchmoq" },
  {
    present: "forget",
    past: "forgot",
    participle: "forgotten",
    uzbek: "unutmoq",
  },
  {
    present: "forgive",
    past: "forgave",
    participle: "forgiven",
    uzbek: "kechirmoq",
  },
  { present: "get", past: "got", participle: "gotten", uzbek: "olmoq" },
  { present: "give", past: "gave", participle: "given", uzbek: "bermoq" },
  { present: "go", past: "went", participle: "gone", uzbek: "bormoq" },
  { present: "grow", past: "grew", participle: "grown", uzbek: "o'smoq" },
  { present: "hang", past: "hung", participle: "hung", uzbek: "osmoq" },
  { present: "have", past: "had", participle: "had", uzbek: "ega bo'lmoq" },
  { present: "hear", past: "heard", participle: "heard", uzbek: "eshitmoq" },
  { present: "hit", past: "hit", participle: "hit", uzbek: "urmoq" },
  { present: "hold", past: "held", participle: "held", uzbek: "ushlamoq" },
  { present: "keep", past: "kept", participle: "kept", uzbek: "saqlamoq" },
  { present: "know", past: "knew", participle: "known", uzbek: "bilmoq" },
  { present: "lay", past: "laid", participle: "laid", uzbek: "qo'ymoq" },
  { present: "lead", past: "led", participle: "led", uzbek: "boshqarmoq" },
  { present: "leave", past: "left", participle: "left", uzbek: "tark etmoq" },
  { present: "lend", past: "lent", participle: "lent", uzbek: "qarz bermoq" },
  { present: "let", past: "let", participle: "let", uzbek: "ruxsat bermoq" },
  { present: "lie", past: "lay", participle: "lain", uzbek: "yotmoq" },
  { present: "lose", past: "lost", participle: "lost", uzbek: "yo'qotmoq" },
  { present: "make", past: "made", participle: "made", uzbek: "yasamoq" },
  { present: "mean", past: "meant", participle: "meant", uzbek: "anglatmoq" },
  { present: "meet", past: "met", participle: "met", uzbek: "uchrashmoq" },
  { present: "pay", past: "paid", participle: "paid", uzbek: "to'lamoq" },
  { present: "put", past: "put", participle: "put", uzbek: "qo'ymoq" },
  { present: "read", past: "read", participle: "read", uzbek: "o'qimoq" },
  { present: "ride", past: "rode", participle: "ridden", uzbek: "minmoq" },
  { present: "ring", past: "rang", participle: "rung", uzbek: "jiringlatmoq" },
  { present: "rise", past: "rose", participle: "risen", uzbek: "ko'tarilmoq" },
  { present: "run", past: "ran", participle: "run", uzbek: "yugurmoq" },
  { present: "say", past: "said", participle: "said", uzbek: "aytmoq" },
  { present: "see", past: "saw", participle: "seen", uzbek: "ko'rmoq" },
  { present: "sell", past: "sold", participle: "sold", uzbek: "sotmoq" },
  { present: "send", past: "sent", participle: "sent", uzbek: "yubormoq" },
  { present: "sing", past: "sang", participle: "sung", uzbek: "kuylamoq" },
  { present: "sit", past: "sat", participle: "sat", uzbek: "o'tirmoq" },
  { present: "sleep", past: "slept", participle: "slept", uzbek: "uxlamoq" },
  { present: "speak", past: "spoke", participle: "spoken", uzbek: "gapirmoq" },
  { present: "spend", past: "spent", participle: "spent", uzbek: "sarflamoq" },
  { present: "stand", past: "stood", participle: "stood", uzbek: "turmoq" },
  {
    present: "steal",
    past: "stole",
    participle: "stolen",
    uzbek: "o'g'irlamoq",
  },
  { present: "swim", past: "swam", participle: "swum", uzbek: "suzmoq" },
  { present: "take", past: "took", participle: "taken", uzbek: "olmoq" },
  {
    present: "teach",
    past: "taught",
    participle: "taught",
    uzbek: "o'rgatmoq",
  },
  { present: "tell", past: "told", participle: "told", uzbek: "aytmoq" },
  {
    present: "think",
    past: "thought",
    participle: "thought",
    uzbek: "o'ylamoq",
  },
  { present: "throw", past: "threw", participle: "thrown", uzbek: "otmoq" },
  {
    present: "understand",
    past: "understood",
    participle: "understood",
    uzbek: "tushunmoq",
  },
  { present: "wear", past: "wore", participle: "worn", uzbek: "kiymoq" },
  { present: "win", past: "won", participle: "won", uzbek: "yutmoq" },
  { present: "write", past: "wrote", participle: "written", uzbek: "yozmoq" },
];
